
// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const LOAD_MY_CONTRACT = 'LOAD_MY_CONTRACT';

// Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Contract
export const LOAD_SOCIAL_BENEFIT = 'LOAD_SOCIAL_BENEFIT';
export const GET_SERVICE_CENTER = 'GET_SERVICE_CENTER';
export const GET_FORM_QUESTIONS = 'GET_FORM_QUESTIONS';
export const SET_SERVICE_CENTER = 'SET_SERVICE_CENTER';
export const SET_FORMULAR = 'SET_FORMULAR';
export const SET_DYNAMIC_FORM_INPUT = 'SET_DYNAMIC_FORM_INPUT';
export const SET_PDF_PATH = 'SET_PDF_PATH';